In [9]:
import numpy as np

In [16]:
ar = np.arange(0, 10, 1)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
type(ar)

numpy.ndarray

# Size of a Numpy Array

In [18]:
print(f"Length : {len(ar)}")
print(f"Size   : {ar.size}")

Length : 10
Size   : 10


In [20]:
ar.size*ar.itemsize

40

In [21]:
ar.nbytes

40

In [24]:
ar_2d = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
ar_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
ar_2d.ndim

2

In [28]:
ar_2d.size

8

# Shape & Reshape an Array

In [30]:
n_ar = np.random.rand(10)
n_ar

array([0.67895999, 0.8801882 , 0.5619744 , 0.77377311, 0.72769127,
       0.28833744, 0.02584603, 0.51628832, 0.06847167, 0.76279085])

In [34]:
print(f"Shape   : {n_ar.shape}")
print(f"N-Dim   : {n_ar.ndim}")
print(f"Length  : {len(n_ar.shape)}")

Shape   : (10,)
N-Dim   : 1
Length  : 1


## 3-D Array

In [35]:
ar_3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
ar_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [36]:
print(f"Shape   : {ar_3d.shape}")
print(f"N-Dim   : {ar_3d.ndim}")
print(f"Length  : {len(ar_3d.shape)}")

Shape   : (1, 3, 3)
N-Dim   : 3
Length  : 3


## Indexing & Slicing of an Array

In [38]:
ar = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
print(f"Shape   : {ar.shape}")
print(f"N-Dim   : {ar.ndim}")
print(f"Length  : {len(ar.shape)}")

Shape   : (3, 4)
N-Dim   : 2
Length  : 2


In [42]:
ar[0][0]

1

In [43]:
ar[0]

array([1, 2, 3, 4])

In [44]:
ar[-1]

array([ 9, 10, 11, 12])

In [45]:
print(f"Element at index [0][0]  : {ar[0][0]}")
print(f"Element at index [0]     : {ar[0]}")
print(f"Element at index [-1]    : {ar[-1]}")

Element at index [0][0]  : 1
Element at index [0]     : [1 2 3 4]
Element at index [-1]    : [ 9 10 11 12]


In [46]:
# Slicing ..

ar[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
ar[1:2, 0:2]

array([[5, 6]])

In [48]:
ar[[0, -1]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [49]:
ar[0:, -1]

array([ 4,  8, 12])

In [50]:
ar[0:3:2, 0:-1:2]

array([[ 1,  3],
       [ 9, 11]])

In [51]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Transpose of an Array

In [53]:
ar = np.array([[10,20,30,40],[50,60,70,80]])
ar

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [54]:
print(f"Shape   : {ar.shape}")

Shape   : (2, 4)


In [56]:
# Transpose ..

ar.T

array([[10, 50],
       [20, 60],
       [30, 70],
       [40, 80]])

In [59]:
print(f"Shape   : {ar.T.shape}")

Shape   : (4, 2)


# Mean, Median, Variance & Std Deviation

In [60]:
pass